### ISSUE TITLE
The prediction in `3_rest_requests_multi_model.ipynb` is opposite to the one in `1_experiment_train.ipynb`

### ISSUE THREAD

**Issue by adelton** [rh-aiservices-bu/fraud-detection#35]
When following https://access.redhat.com/documentation/en-us/red_hat_openshift_ai_self-managed/2.9/html-single/openshift_ai_tutorial_-_fraud_detection_example/index on OpenShift AI 2.9.1, the `1_experiment_train.ipynb` will print in the last cell for the input
```
sally_transaction_details = [
    [0.3111400080477545,
    1.9459399775518593, 
    1.0, 
    0.0, 
    0.0]
    ]
```
output
```
Is Sally's transaction predicted to be fraudulent? (true = YES, false = NO) 
False
How likely was Sally's transaction to be fraudulent? 
0.00038%
```
If I add
```
print(prediction)
```
there I will see
```
[array([[0.00038084]], dtype=float32)]
```

When I then save the model to MinIO with `2_save_model.ipynb`, deploy it using a multi-model serving, and use `3_rest_requests_multi_model.ipynb`, for (what seems like) the same input
```
data = [0.3111400080477545, 1.9459399775518593, 1.0, 0.0, 0.0]
```
I get
```
[0.9950703]
```
and
```
fraud
```

It is quite unexpected that the model gives quite the opposite result when run locally and when served.

**Comment by adelton** [comment]
I now tested this with OpenShift AI 2.8.3 and the v2.8.0 tag repo content -- the result is the same.

**Comment by RHRolun** [comment]
Hi,
The difference seems to come from the scaler.transform in 1_experiment_train.ipynb. I'm not sure why it's not included in the 3_rest_request notebook as well, I'll create a PR.

**Comment by RHRolun** [comment]
PR here: #36

**Comment by adelton** [comment]
Fixed via https://github.com/rh-aiservices-bu/fraud-detection/pull/36.
