### ISSUE TITLE
The percentages calculation looks to be missing a `* 100`

### ISSUE THREAD

**Issue by jiridanek** [rh-aiservices-bu/fraud-detection#52]
https://github.com/rh-aiservices-bu/fraud-detection/blob/7b42799d2072531f5787f8057b5024e9321a4c95/1_experiment_train.ipynb#L553

I think this should read

```python
print("{:.5f}".format(np.squeeze(prediction) * 100) + "%")
```

so that the result is between 0 and 100 as a proper percentage, and not from 0 to 1.

**Comment by cfchase** [comment]
Fixed in #50
